controllers/AccountcController.php
<?php

namespace app\controllers;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\widgets\ActiveForm;
use app\models\User;
use app\models\Users;
use app\models\McTcarga;
use app\models\McThideload;
use app\models\McTproposal;
use app\models\McTcompany;
use app\models\McTbank;
use app\models\McTlogin;
use app\models\McTcategory;
use app\models\McTsubcategory;
use app\models\McTcategorySubcategory;
use app\models\McTcompanyservices;
use app\models\McTfriendship;
use app\models\McTvehicle;
use app\models\McTvehicletype;
use app\models\McTreferences;
use app\models\McTcontract;
use app\models\FormChangePasswordCompany;
use app\models\McTcotizaremp;
use app\models\FormCotizarEmp;
use app\models\McTloadproposal;
use app\models\McUloadproposal;
use app\models\FormTransporterPayment;
use app\models\McTcontractemp;
use app\models\McTloadstatus;
use app\models\McTuserchattrans;
use app\models\McTuserchat;
use yii\web\ForbiddenHttpException;
use app\models\McTnotificaciones;

class AccountcController extends \yii\web\Controller
{

	public $layout = "session-company";
	public $enableCsrfValidation = false;

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'sendproposal', 'hideload', 'cotizar','update','delete',
                        'friendship','tranporterprofile','miscargas','usertcontract','userucontract',
                        'seecotization','tranportershortprofile','sendtproposal','listtproposal',
                        'acepttproposal','deletetproposal','listuproposal','senduproposal',
                        'aceptutproposal','deleteutproposal','confirm','transporterchat',
                        'endtproposal'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                          return User::isCompany(Yii::$app->user->identity->id);
                      },
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['get'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $company = McTcompany::find()->where(['fklogin'=>Yii::$app->user->id])->one();
        Yii::$app->session->set('company', $company->pkcompany);
    	Yii::$app->session->set('option', 1);
        $transporter = McTlogin::find()->where(['role'=>4])->all();
        return $this->render('index',['transporter'=>$transporter,'msg'=>'']);
    }

    /*
    *   Funcion que permite ver cotizaciones de usuario
    *   y enviar cotizaciones a transportadores
    *   Creado por: Rodrigo Boet
    *   Fecha: 25/06/2016
    *   @param $type Recibe el tipo de acción
    *   @return Dependiendo del tipo regresa un render a las vistas cotizar o cotizart
    */
    public function actionCotizar($type=null)
    {
    	Yii::$app->session->set('option', 2);
    	$option = 1;
        if($type)
        {
            $msg = '';
            $model = new FormCotizarEmp;
            if(Yii::$app->request->post())
            {   
                $model->load(Yii::$app->request->post());
                if($model->validate()){
                    $company = McTcompany::find()->where(['fklogin' => Yii::$app->user->id])->one();
                    $cotizaremp = new McTcotizaremp;
                    $cotizaremp->origen = $model->origin;
                    $cotizaremp->destino = $model->destination;
                    $cotizaremp->fk_vehicletype = $model->fk_vehicletype;
                    $cotizaremp->weight = $model->weight;
                    $cotizaremp->payment = $model->payment;
                    $cotizaremp->vehicle_number = $model->vehicle_number;
                    $cotizaremp->comment = $model->comment;
                    $cotizaremp->origin_latitude = $model->latitude_orig;
                    $cotizaremp->origin_longitude = $model->longitude_orig;
                    $cotizaremp->destination_latitude = $model->latitude_dest;
                    $cotizaremp->destination_longitude = $model->longitude_dest;
                    $cotizaremp->fkcompany = $company->pkcompany;
                    $cotizaremp->fkstatus = 1;
                    $cotizaremp->send_all = $model->alltcheck;
                    $cotizaremp->save();
                    $msg = 'Se creo la cotización éxitosamente';
                }
                else
                {
                    $msg = 'Ocurrió un error';
                }
                $model = new FormCotizarEmp;
                $vtype = McTvehicletype::find()->all();
                return $this->render('cotizart', ['option'=>$option,'model'=>$model,'vtype'=>$vtype,
                    'msg'=>$msg]);
            }
            else
            {
                $vtype = McTvehicletype::find()->all();
                return $this->render('cotizart', ['option'=>$option,'model'=>$model,'vtype'=>$vtype,
                    'msg'=>$msg]);
            }
        }
        else
        {
        	$sql = 'SELECT carga.* FROM mc_tcarga carga';
        	$sql .= " WHERE NOT EXISTS (SELECT 1 FROM mc_thideload hide 
                      WHERE hide.fkload = carga.pkload AND hide.fkcompany =
                      ".Yii::$app->session->get("userid").")";
    		$sql .= " GROUP BY carga.pkload ORDER BY carga.load_create DESC";
    		$loads = McTcarga::findBySql($sql)->all();
            return $this->render('cotizar', ['option'=>$option, 'loads'=>$loads]);
        }
    }

    public function actionHideload(){
    	if(isset($_POST["lid"])){
    		$hide = new McThideload;
    		$hide->fkload = $_POST["lid"];
    		$hide->fkcompany = Yii::$app->session->get("userid");
    		$hide->insert();
    		return $this->redirect(['accountc/cotizar']);
    	}else{
        	return $this->redirect(['accountc/']);
        }
    }

    public function actionSendproposal(){
    	if(isset($_POST["lid"])){
    		$option = 1;
    		$prop = new McTproposal;
    		$prop->fkload = $_POST["lid"];
    		$prop->fkcompany = Yii::$app->session->get("userid");
    		$prop->proposal_total = $_POST["vp"];
    		$prop->proposal_paymin = $_POST["pm"];
    		$prop->insert();
    		$sql = 'SELECT carga.* FROM mc_tcarga carga';
	    	$sql .= " WHERE NOT EXISTS (SELECT 1 FROM mc_thideload hide 
	                  WHERE hide.fkload = carga.pkload)";
			$sql .= " GROUP BY carga.pkload";
			$loads = McTcarga::findBySql($sql)->all();
            $load =  McTcarga::find()->where(["pkload" => $_POST["lid"]])->one();
            $utmp = $load->getFkuser0()->One();
			$msg = "La cotización ha sido enviada";
            //Notificación
            $user = McTlogin::find()->where(['id'=> $load->fkuser0->fklogin0->id])->one();
            $company = McTcompany::find()->where(['fklogin'=>Yii::$app->user->id])->one();
            $model_notificacion = new McTnotificaciones();
            $model_notificacion->fk_login=$user->id;
            $model_notificacion->msj_notificacion="La empresa <b>". $company->company_rz ."</b> te envío una propuesta <a href='".Yii::getAlias('@web')."/account/detalle/".$prop->fkload."' onclick='modalClick(event)'> Ver Propuesta</a>";
            $model_notificacion->activa=1;
            $model_notificacion->save();
            /*$subject = "Has recibido la Cotización para el servicio de transporte que necesitas.";
            Yii::$app->mailer->compose('new_cot_company', 
                [
                    'name'=>$utmp->user_name,
                    'origin'=>$load->load_cityorigin,
                    'destination'=>$load->load_citydestination,
                    'sub'=>$load->getFksubcategory0()->One()->subcategory_name,
                    'link'=>'http://micargapp.com'. Yii::getAlias('@web').'/account/detalle/'.$_POST["lid"]
                ])
             ->setTo($utmp->getFklogin0()->One()->email2)
             ->setFrom([Yii::$app->params["adminEmail"] => Yii::$app->params["title"]])
             ->setSubject($subject)
             ->send();*/
             $_POST = array();    		
             return $this->render('cotizar',['option'=>$option, 'loads'=>$loads, 'msg'=>$msg]);
    	}else{
        	return $this->redirect(['accountc/']);
        }
    }

    /*
    *   Funcion que permite actualizar el perfil de la empresa
    *   Creado por: Rodrigo Boet
    *   Fecha: 06/06/2016
    *   @param $id Recibe el id de la compañia
    *   @param $id_login Recibe el id del usuario
    *   @return Regresa un render de la vista update
    */
    public function actionUpdate($id,$id_login)
    {
        Yii::$app->session->set('option', 4);
        if(Yii::$app->user->id==$id_login)
        {
            $msg = '';   
            $form_register = new FormChangePasswordCompany;
            $model = McTcompany::findOne($id);
            $user = McTlogin::findOne($id_login);
            $services = McTcompanyservices::find()->where(['fkcompany'=>$id])->asArray()->all();
            if(Yii::$app->request->post())
            { 
                $previous_avatar = $model->company_avatar;
                if ($form_register->load(Yii::$app->request->post()) && Yii::$app->request->isAjax)
                {
                    Yii::$app->response->format = Response::FORMAT_JSON;
                    return ActiveForm::validate($form_register);
                }
                if ($form_register->load(Yii::$app->request->post()))
                {
                    if($form_register->validate())
                    {
                        $user->email2 = $form_register->email;
                        $model->company_rz = $form_register->rz;
                        $model->company_nit = $form_register->nit;

views/accountc/cotizar.php
<?php 
  use app\models\McTcategory;
  use app\models\McTcompanyservices;
  use app\models\McTproposal;
  use yii\helpers\Html;
?>
<div class="content">
  <div class="container">
    <div class="row white administration-navigation-wrapper">
      <div class="main">
        <div class="row ">
          <div class="col-lg-12">
          <?= Html::a('CLIENTES', ['cotizar'], ['class' => 'btn btn-active btn-sub2 top-button col-md-2 col-xs-12 col-sm-3 col-lg-21']) ?>
          <?= Html::a('TRANSPORTADOR', ['cotizar','type'=>1], ['class' => 'btn btn-desactive btn-sub2 top-button col-md-2 col-xs-12 col-sm-3 col-lg-2']) ?>
         </div>
        </div>
        <div class="clearfix"></div>
          <div class="part3 col-lg-5 col-xs-12 right-side">
            <div class="col-md-2  form-title">Buscar:</div>
              <div class="col-md-5 col-xs-5">
                <?= yii\jui\DatePicker::widget(['name' => 'srch_date', 'dateFormat' => 'dd-MM-yyyy']) ?>
              </div>
              <div class="col-md-5 col-xs-5">
                <button type="submit" class="btn btn-primary submit">BUSCAR</button>
              </div>
          </div><br>
        <div class="blocks">
          <?php 
            if(isset($msg)) 
              echo "<center><h3 class='confirm'>$msg</h3></center><br>"; 
          ?>
          <?php foreach ($loads as $l) {?>
            <?php $user = $l->getFkuser0()->One(); ?>
            <?php $catg = McTcategory::find($l->getFksubcategory0()->One()->fkcategory)->One(); ?>
            <?php 
              $comi = McTcompanyservices::find()
                    ->where("fkcompany=:id", [":id" => Yii::$app->session->get("userid")])
                    ->andWhere('fksubcategory = :sub', [':sub' => $l->getFksubcategory0()->One()->pktcategory_subcategory])
                    ->one();
              $pexist = McTproposal::find()
                    ->where("fkcompany=:id", [":id" => Yii::$app->session->get("userid")])
                    ->andWhere('fkload = :load', [':load' => $l->pkload])
                    ->one();
              if($comi){
            ?>
            <div class="col-lg-12 qoute-main-block">
              <div class="row administration-side administration-side-activity qoute-inner-block margin-4">
                <div class="col-sm-6 col-xs-12 administration-activity-info ">
                  <div class="row">
                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                      <img src="<?php echo Yii::getAlias('@web') . $user->user_avatar; ?>">
                    </div>
                    <div class="col-lg-8 col-md-8 col-sm-9 col-xs-9">
                         <p class="large-title"><?php echo $user->user_name; ?></p>
                        <div class="type col-log-6">
                         <p><span class="type-text">Categoria:</span>  <span class="green"><?php echo $catg->category_name;?></span></p>
                         <p><span class="type-text">Sub-Catg:</span> <span class="green"><?php echo $l->getFksubcategory0()->One()->fksubcategory0->subcategory_name; ?></span></p>
                         <p><span class="type-text">Asegura:</span>  <span class="red">$ <?php echo number_format($l->load_ensure); ?></span></p>
                        </div>                    
                    </div>
                  </div>
                </div>
              <div class="col-sm-6 col-sm-offset-0 col-xs-offset-2 quote-box">
                  <div class="contract-box ">
              <form>
                <div class="type col-sm-8">
                <p><span class="width-box">Fecha orden:</span>    <span id="fecha" style="font-weight:bolder" class="blue"><?php echo date("d-m-Y",  strtotime($l->load_create));?></span></p>
                <p>
                  <span class="width-box">Valor a Pagar:</span>  
                  <span class="<?php echo $pexist ? "" : "blue"; ?>">
                    <?php 
                      if($pexist) 
                        echo '$ ' . number_format($pexist->proposal_total) . ' COP';
                      else{?>
                      <input type="number" class="textbox-field vp<?php echo $l->pkload; ?>">
                      <span class="field_title">COP</span>
                    <?php } ?>
                  </span>
                </p>
                <p>
                  <span class="width-box">Pago Minimo:</span> 
                  <span class="<?php echo $pexist ? "" : "blue"; ?>">
                    <?php 
                      if($pexist) 
                        echo '$ ' . number_format($pexist->proposal_paymin) . ' COP';
                      else{?>
                      <input type="number" class="textbox-field pm<?php echo $l->pkload; ?>">
                      <span class="field_title">COP</span>
                    <?php } ?>
                  </span>
                </p>
                <p><span class="width-box">% Comisión:</span>  <span class="blue bold-large"> <?php echo $comi->companyservices_percent; ?>%</span> </p>
              </div>
              <div class="type col-sm-4"> 
              <?php if(!$pexist) {?>
               <button type="button" class="btn btn-active submit quote-btn btn-act btn-cotizar" id="<?php echo $l->pkload; ?>">COTIZAR</button>
              <?php }?>
              </div>
               </form>
              </div>
              </div>
            </div>
            <div class="row administration-side administration-side-activity qoute-inner-block">
              <div class="col-sm-10 col-xs-12 administration-activity-info small-padding-around">
                <div class="row">
                  <div class="col-lg-6 col-md-6 col-sm-5">
                   <div class="description-block">
                    <p><span class="width-box"><strong>Desde:</strong></span><span><?php echo $l->load_cityorigin; ?></span></p>
                    <p><span class="width-box"><strong>Hasta:</strong></span><span><?php echo $l->load_citydestination; ?></span></p>
                     <p><span class="width-box"><strong>Tipo:</strong></span><span>No definido</span></p>
                      <p><span class="width-box"><strong>Peso:</strong></span><span><?php echo $l->load_weight < 1000 ? $l->load_weight . " Kl" : ($l->load_weight / 1000) . " Ton" ?></span></p>
                   </div>
                  </div>
                  <div class="col-lg-6 col-md-6 col-sm-5">
                      <div class="Dimensiones-block">
                    <p><span class="width-box"><strong>Dimensiones:</strong></span><span><?php echo $l->load_dimensions; ?></span></p>
                    <p><span class="width-box"><strong>Observaci&oacute;n:</strong></span><span class="observation-text"><?php echo $l->load_comment; ?></span></p>
                   </div>                
                  </div>
                </div>
              </div>
              <div class="col-sm-2 col-sm-offset-0  Remove-box">
                <?php if(!$pexist) {?>
                 <button type="submit" class="btn btn-primary submit remove-btn" id="<?php echo $l->pkload; ?>">ELIMINAR</button>
                <?php }?>
              </div>
            </div>
          </div>
          <?php } ?>
          <?php } ?>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {  
    $(".remove-btn").click(function(){
      var id = $(this).attr("id");
      //var baseUrl = "http://micargapp.com/web";
      swal({   
        title: "¿Está seguro de eliminar esta cotización?",   
        text: " La acción no podrá deshacerse!",   
        type: "warning",   
        showCancelButton: true,   
        confirmButtonColor: "#ff6b6b",   
        cancelButtonText: "Cancelar", 
        confirmButtonText: "Si, Eliminar!",   
        closeOnConfirm: true 
      }, function(){   
          var params = {lid : id};
          var body = document.body;
          form = document.createElement('form');
          form.method = 'POST';
          form.action = url + "/accountc/hideload";
          form.name = 'jsform';
          for (index in params) {
            var input = document.createElement('input');
            input.type = 'hidden';
            input.name = index;
            input.id = index;
            input.value = params[index];
            form.appendChild(input);
          }
          body.appendChild(form);
          form.submit();
      });
    });
    $(".btn-cotizar").click(function(){
      var id = $(this).attr("id");
      //var baseUrl = "http://micargapp.com/web";
      var vp = $(".vp" + id).val();
      var pm = $(".pm" + id).val();
      if(vp == ""){
         $(".vp" + id).attr("style","border: 1px solid #a94442 !important;");
         $(".pm" + id).removeAttr("style");
         return;
      }
      if(pm == ""){
        $(".pm" + id).attr("style","border: 1px solid #a94442 !important;");
        $(".vp" + id).removeAttr("style");
        return;
      }
      $(".pm" + id).removeAttr("style");
      $(".vp" + id).removeAttr("style");
      swal({   
        title: "¿Está seguro de enviar la cotización?",   
        text: "Una vez enviada no puede ser modificada",   
        type: "warning",   
        showCancelButton: true,   
        confirmButtonColor: "#65b3fe",   
        cancelButtonText: "Cancelar", 
        confirmButtonText: "Si, Enviar!",   
        closeOnConfirm: true 
      }, function(){   
          var params = {
            lid : id,
            vp: vp,
            pm: pm
          };
          var body = document.body;
          form = document.createElement('form');
          form.method = 'POST';
          form.action = url + "/accountc/sendproposal";
          form.name = 'jsform';
          for (index in params) {
            var input = document.createElement('input');
            input.type = 'hidden';
            input.name = index;
            input.id = index;
            input.value = params[index];
            form.appendChild(input);
          }
          body.appendChild(form);
          form.submit();
      });
    });
  });
 $('.submit').click(function(event){
    event.preventDefault();
    $('.qoute-main-block').each(function(index,value){
      $(this).show();
    });
    var value_date = $('#w0').val();
    $('.blocks').find('.not-found').remove();
    if(value_date)
    {
      $('.qoute-main-block').each(function(index,value){
        var bool = false;
        var m = $(value).find('#fecha').text()===value_date;
        (m===true) ? bool = true: bool = false;
        console.log(m);
        if(!bool)
        {
          $(this).hide();
        }
      });
    }
    else
    {
      $('.qoute-main-block').each(function(index,value){
        $(this).show();
      });
    }
    var bool=true;
    $('.qoute-main-block').each(function(index,value){
      $(this).attr('style')!="display: none;" ? bool=false:'';
    });
    if(bool && value_date)
    {
      var txt ='<div class="row not-found" style="background-color: #fff;"><div class="page-header">';
      txt+='<h1><small class="small-block mt"><strong>No se encontraron resultados!</strong></small>';
      txt+='</h1></div></div>';
      $('.qoute-main-block').parent().append(txt);
    }
  });
</script>

views/accountc/cotizart.php
<?php 
  use yii\helpers\Html;
  use yii\helpers\ArrayHelper;
  use yii\widgets\ActiveForm;
?>
<div class="content">
  <div class="container">
    <div class="row white administration-navigation-wrapper">
      <div class="main">
        <div class="row">
          <div class="col-lg-12">
          <?= Html::a('CLIENTES', ['cotizar'], ['class' => 'btn btn-desactive btn-sub2 top-button col-md-2 col-xs-12 col-sm-3 col-lg-2']) ?>
          <?= Html::a('TRANSPORTADOR', ['cotizar','type'=>1], ['class' => 'btn btn-active btn-sub2 top-button col-md-2 col-xs-12 col-sm-3 col-lg-2']) ?>
         </div>
        </div>
        <?php if($msg) echo '<h3 class="confirm">' . $msg . '</h3>';?>
        <div class="blocks administration-right-side-wrapper">
          <div class="col-sm-4"></div>
          <div class="col-sm-4">
            <div class="col-xs-12 administration-side new-user-za">
              <h1 class="text-center">Cotizar Carga</h1><hr>
            </div>
            <div class="accountc-FormCotizarEmp">

              <?php $form = ActiveForm::begin([
                'enableClientValidation' => true,
                'action' => ['cotizar', 'type' => '1'],
              ]); ?>

                  <?= $form->field($model, 'origin')->input("text", ['placeholder' => 'Lugar Origen', 'class' => 'administration-input'])->label(false) ?>
                  <?= $form->field($model, 'destination')->input("text", ['placeholder' => 'Lugar Destino', 'class' => 'administration-input'])->label(false) ?>
                  <?= $form->field($model, 'fk_vehicletype')->dropDownList(ArrayHelper::map($vtype,'pkvehicletype','vehicletype_name'), ['prompt'=>'Tipo de Vehículo', 'class' => 'administration-input'])->label(false); ?>
                  <?= $form->field($model, 'weight')->input("text", ['placeholder' => 'Peso', 'class' => 'administration-input'])->label(false) ?>
                  <?= $form->field($model, 'payment')->input("number", ['placeholder' => 'Valor a Pagar por Vehículo', 'class' => 'administration-input'])->label(false) ?>
                  <?= $form->field($model, 'vehicle_number')->input("number", ['placeholder' => 'Número de Vehículos', 'class' => 'administration-input', 'min'=>'0'])->label(false) ?>
                  <?= $form->field($model, 'comment')->textarea(['placeholder' => 'Comentarios', 'class' => 'administration-input'])->label(false) ?>
                  <div id="mapid" style="height: 180px;"></div>
                  <div class="row">
                    <div class="col-md-6">
                      <?= $form->field($model, 'latitude_orig')->textInput(['placeholder' => 'Latitud', 'class' => 'administration-input form-field', 'readonly'=>true])->label(false); ?>
                    </div>
                    <div class="col-md-6">
                      <?= $form->field($model, 'longitude_orig')->textInput(['placeholder' => 'Longitud', 'class' => 'administration-input form-field', 'readonly'=>true])->label(false); ?>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-6">
                      <?= $form->field($model, 'latitude_dest')->textInput(['placeholder' => 'Latitud', 'class' => 'administration-input form-field', 'readonly'=>true])->label(false); ?>
                    </div>
                    <div class="col-md-6">
                      <?= $form->field($model, 'longitude_dest')->textInput(['placeholder' => 'Longitud', 'class' => 'administration-input form-field', 'readonly'=>true])->label(false); ?>
                    </div>
                  </div>
                  <?= $form->field($model, 'alltcheck')->checkbox(['value'=>'1', 'label'=>'Envíar a Todos mis conductores'])->label(false) ?>
              
              

          </div><!-- accountc-FormCotizarEmp -->
            <div class="col-xs-12 administration-submit">
              <?= Html::submitButton('COTIZAR CARGA', ['class' => 'btn btn-active col-xs-12']) ?>
            </div>
          </div>

          <?php ActiveForm::end(); ?>

          <div class="col-sm-4"></div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  var mymap = L.map('mapid').setView([4.59772, -74.07656], 13);
  L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
    maxZoom: 18,
    id: 'rudmanmrrod.0f8gf90d',
    accessToken: 'pk.eyJ1IjoicnVkbWFubXJyb2QiLCJhIjoiY2lwcG5ja29lMDQ0emZqbTNuazRrZWxuciJ9.yYp783TnZbC7HxeIC8v96g'
}).addTo(mymap)

  var redMarker = L.AwesomeMarkers.icon({ markerColor: 'red' });
  var blueMarker = L.AwesomeMarkers.icon({icon:'pushpin', markerColor: 'blue' });

  var origin = L.marker([0,0],{icon: blueMarker,title:'Origen'}).addTo(mymap);
  var destination = L.marker([0,0], {icon: redMarker, title:'Destino'}).addTo(mymap);

  var OriginControl = L.Control.extend({
 
    options: {
      position: 'topright' 
      //control position - allowed: 'topleft', 'topright', 'bottomleft', 'bottomright'
    },
   
    onAdd: function (map) {
      var container = L.DomUtil.create('div', 'leaflet-bar leaflet-control leaflet-control-custom');
      $(container).append("<i class='glyphicon glyphicon-pushpin' style='top:8px;left:8px;'></i>");
      $(container).attr('name','origin-point');
      $(container).attr('title','Origen');
      L.DomEvent.on(container, 'mousedown dblclick', L.DomEvent.stop)
      .on(container, 'click', L.DomEvent.stop);
   
      container.style.backgroundColor = 'white';
      container.style.width = '30px';
      container.style.height = '30px';
      return container;
    },
  });

  var DestinationControl = L.Control.extend({
 
    options: {
      position: 'topright',
      title: 'Destino', 
      //control position - allowed: 'topleft', 'topright', 'bottomleft', 'bottomright'
    },
   
    onAdd: function (map) {
      var container = L.DomUtil.create('div', 'leaflet-bar leaflet-control leaflet-control-custom');
      $(container).append("<i class='glyphicon glyphicon-home' style='top:8px;left:8px;'></i>");
      $(container).attr('name','destination-point');
      $(container).attr('title','Destino');
      L.DomEvent.on(container, 'mousedown dblclick', L.DomEvent.stop)
      .on(container, 'click', L.DomEvent.stop);
   
      container.style.backgroundColor = 'white';
      container.style.width = '30px';
      container.style.height = '30px';
      return container;
    },
  });



  function onMapClick(e) {
    var text = $('.selected').attr('name');
    if(text=="origin-point")
    {
      origin.setLatLng(e.latlng);
      $('#formcotizaremp-latitude_orig').val(e.latlng.lat);
      $('#formcotizaremp-longitude_orig').val(e.latlng.lng);
    }
    else if(text=="destination-point")
    {
      destination.setLatLng(e.latlng);
      $('#formcotizaremp-latitude_dest').val(e.latlng.lat);
      $('#formcotizaremp-longitude_dest').val(e.latlng.lng);
    }
    console.log(e.latlng);
  }

  mymap.addControl(new OriginControl());
  mymap.addControl(new DestinationControl());
  mymap.doubleClickZoom.disable(); 
  mymap.on('click', onMapClick);

  $(document).ready(function(){
    $('.leaflet-control-custom').click(function(){
      var attribute = $(this).attr('class');
      if(attribute.search('selected')!=-1)
      {
        $(this).removeClass('selected');
        $(this).css('background-color','white');
      }
      else
      {
        var anterior = $('.leaflet-right').find('.selected');
        $(anterior).removeClass('selected');
        $(anterior).css('background-color','white');
        $(this).addClass('selected');
        $(this).css('background-color','gray');
      }
    });
});
</script>